# Use the official Python image as a base
FROM python:3.10

# Set the working directory in the container
WORKDIR /app

# Copy the requirements file to the container
COPY requirements.txt ./ 

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy the entire application to the container
COPY . .

# Expose the Streamlit port
EXPOSE 8501

# Command to run the Streamlit app
ENTRYPOINT ["streamlit", "run"]

# Specify the main script to run
CMD ["app.py"]
